# Generated by Django 4.2 on 2023-04-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='extra_info',
            field=models.TextField(default=''),
        ),
    ]
